#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <stdint.h>

// CONFIGURABLE PARAMETERS
#define NUM_REAL_DATA_BLOCKS_AS_POWER_OF_2 20U
#define NUM_BLOCKS_PER_BUCKET 4U
#define NUM_BYTES_PER_BLOCK 8U
#define NUM_EXPERIMENT_ACCESSES (1U << 18U)
#define QUERY_RANGE_SIZE 1


// DO NOT CHANGE SUBSEQUENT MACRO VALUES DIRECTLY
#define NUM_TOTAL_REAL_BLOCKS (1U << NUM_REAL_DATA_BLOCKS_AS_POWER_OF_2)
#define HEIGHT_OF_TREE NUM_REAL_DATA_BLOCKS_AS_POWER_OF_2
#define NUM_TOTAL_BUCKETS ((1U << (HEIGHT_OF_TREE + 1)) - 1)
#define STASH_SIZE (303U + NUM_REAL_DATA_BLOCKS_AS_POWER_OF_2)
// 303 was taken from Section 6.4 Fig. 5 as the required max size for a 256-bit
// security parameter excluding the path initially retrieved from an access.

#define NUM_BYTES_FOR_PATH_ID 4U
#define NUM_BYTES_FOR_BLOCK_ID 4U
#define NUM_BYTES_PER_BLOCK_AND_METADATA                                       \
  (NUM_BYTES_FOR_BLOCK_ID + NUM_BYTES_FOR_PATH_ID + NUM_BYTES_PER_BLOCK)

#define AES_KEY_SIZE_BYTES 32U
#define AES_IV_SIZE_BYTES 12U
#define AES_TAG_SIZE_BYTES 16U
#define NUM_BYTES_PER_ENCRYPTED_BLOCK                                          \
  (AES_IV_SIZE_BYTES + NUM_BYTES_PER_BLOCK_AND_METADATA + AES_TAG_SIZE_BYTES)



#endif
