#ifndef PARAMETERS_H
#define PARAMETERS_H

// CONFIGURABLE PARAMETERS
#define NUM_REAL_DATA_BLOCKS_AS_POWER_OF_2 20U
#define NUM_BLOCKS_PER_BUCKET 4U
#define NUM_DATA_BYTES_PER_BLOCK 32U
#define NUM_EXPERIMENT_ACCESSES (1U << 10U)

// BOTH SHOULD BE SPECIFIED AND EQUIVALENT
#define QUERY_RANGE_SIZE 64U
#define QUERY_RANGE_SIZE_AS_POWER_OF_2 6U

#endif
